/**
 * Shared constants for the public landing page.
 *
 * Screenshots are generated by `npm run screenshots` into `public/screenshots/`. They
 * are referenced by path rather than by static import so the build does not depend on
 * them being present, and they are regenerable in one command, which matters because a
 * stale screenshot is worse than no screenshot.
 */

export const GITHUB_URL = 'https://github.com/jgbattung/MoneyMap'

/** Captured at 1440x900 with deviceScaleFactor 2. */
export const SHOT_WIDTH = 2880
export const SHOT_HEIGHT = 1800

export const SHOTS = {
  dashboard: '/screenshots/dashboard.png',
  accounts: '/screenshots/accounts.png',
  cards: '/screenshots/cards.png',
  transactions: '/screenshots/transactions.png',
  budgets: '/screenshots/budgets.png',
  calendar: '/screenshots/calendar.png',
  reports: '/screenshots/reports.png',
} as const
