/**
 * Shared constants for the public landing page.
 *
 * Screenshots are generated by `npm run screenshots` (against a production build, see
 * `npm run start:demo`) into `public/screenshots/desktop/` and `public/screenshots/mobile/`.
 * They are referenced by path rather than by static import so the build does not depend
 * on them being present, and they are regenerable in one command, which matters because
 * a stale screenshot is worse than no screenshot.
 */

export const GITHUB_URL = 'https://github.com/jgbattung/MoneyMap'

/** Desktop set: captured at 1440x900 with deviceScaleFactor 2. */
export const SHOT_WIDTH = 2880
export const SHOT_HEIGHT = 1800

/** Mobile set: captured at 390x844 (a real device profile) with deviceScaleFactor 3. */
export const SHOT_WIDTH_MOBILE = 1170
export const SHOT_HEIGHT_MOBILE = 2532

const SLUGS = [
  'dashboard',
  'accounts',
  'card-detail',
  'transactions',
  'calendar',
  'budgets',
  'net-worth',
  'reports',
  'event-ledger',
] as const

type Slug = (typeof SLUGS)[number]

function shotsFor(device: 'desktop' | 'mobile'): Record<Slug, string> {
  return Object.fromEntries(
    SLUGS.map((slug) => [slug, `/screenshots/${device}/${slug}.png`])
  ) as Record<Slug, string>
}

/** Full nine-surface set, one path per device, for the landing page rebuild to consume
 *  with its desktop/mobile toggle (Amendment 1). */
export const SHOTS_DESKTOP = shotsFor('desktop')
export const SHOTS_MOBILE = shotsFor('mobile')

/**
 * Backward-compatible alias for the current (pre-rebuild) landing page sections, which
 * predate the desktop/mobile toggle and the reworked surface list. Points at the
 * desktop set. `cards` now resolves to the individual card detail capture (`card-detail`)
 * and `reports` to the net-worth overview capture (`net-worth`), since those are the
 * correct content replacements for what those keys used to mean - the section-to-image
 * mapping itself is left untouched, pending the design-review rebuild.
 */
export const SHOTS = {
  dashboard: SHOTS_DESKTOP.dashboard,
  accounts: SHOTS_DESKTOP.accounts,
  cards: SHOTS_DESKTOP['card-detail'],
  transactions: SHOTS_DESKTOP.transactions,
  budgets: SHOTS_DESKTOP.budgets,
  calendar: SHOTS_DESKTOP.calendar,
  reports: SHOTS_DESKTOP['net-worth'],
} as const
