/**
 * Shared constants for the public landing page.
 *
 * Screenshots are generated by `npm run screenshots` (against a production build, see
 * `npm run start:demo`) into `public/screenshots/desktop/` and `public/screenshots/mobile/`.
 * They are referenced by path rather than by static import so the build does not depend
 * on them being present, and they are regenerable in one command, which matters because
 * a stale screenshot is worse than no screenshot.
 */

export const GITHUB_URL = 'https://github.com/jgbattung/MoneyMap'

/** Desktop set: captured at 1440x900 with deviceScaleFactor 2. */
export const SHOT_WIDTH = 2880
export const SHOT_HEIGHT = 1800

/** Mobile set: captured at 390x844 (a real device profile) with deviceScaleFactor 3. */
export const SHOT_WIDTH_MOBILE = 1170
export const SHOT_HEIGHT_MOBILE = 2532

const SLUGS = [
  'dashboard',
  'accounts',
  'card-detail',
  'transactions',
  'calendar',
  'budgets',
  'net-worth',
  'reports',
  'event-ledger',
] as const

type Slug = (typeof SLUGS)[number]

function shotsFor(device: 'desktop' | 'mobile'): Record<Slug, string> {
  return Object.fromEntries(
    SLUGS.map((slug) => [slug, `/screenshots/${device}/${slug}.png`])
  ) as Record<Slug, string>
}

/** Full nine-surface set, one path per device, consumed by the feature sections' phone
 *  frames and the hero's desktop/phone composition. */
export const SHOTS_MOBILE = shotsFor('mobile')

/**
 * Category Breakdown is captured desktop only (Amendment 3: the Reports section
 * dropped its three-image bento in favour of a single desktop capture), so it is
 * added directly to the desktop set rather than the shared per-device `SLUGS` loop,
 * which has no mobile counterpart for it.
 */
export const SHOTS_DESKTOP: Record<Slug, string> & { 'category-breakdown': string } = {
  ...shotsFor('desktop'),
  'category-breakdown': '/screenshots/desktop/category-breakdown.png',
}
