import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared/Sidebar";
import { Toaster } from "@/components/ui/sonner";
import BottomBar from "@/components/shared/BottomBar";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MoneyMap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <main className="flex h-screen">
            {/* Desktop Sidebar */}
            <Sidebar />
            
            {/* Content Area */}
            <div className="flex-1 overflow-auto">
              {children}
            </div>
            
            {/* Mobile Bottom Bar */}
            {/* <BottomBar className="md:hidden" /> */}
            <Toaster position="bottom-right"/>
            <BottomBar />
          </main>
        </Providers>
      </body>
    </html>
  );
}