import {
  IconLogin,
  IconLogout,
  IconCoinMoneroFilled,
  IconBrandGoogle,
  IconBrandFacebook,
  IconPlus,
  IconMinus,
  IconArrowRight,
  IconLibraryPlusFilled,
  IconCashBanknotePlus,
  IconTrendingUp,
  IconWallet,
  IconExclamationCircleFilled,
  IconChevronUp,
  IconCreditCard,
  IconMoneybag,
  IconBuildingBank,
  IconChartBarPopular,
  IconDotsVertical,
  IconPencil,
  IconTrash,
} from '@tabler/icons-react';



export const Icons = {
  logOut: IconLogout,
  logIn: IconLogin,
  logo: IconCoinMoneroFilled,
  google: IconBrandGoogle,
  facebook: IconBrandFacebook,
  addExpense: IconMinus,
  addIncome: IconPlus,
  addTransfer: IconArrowRight,
  createAccount: IconLibraryPlusFilled,
  accountIcon: IconCashBanknotePlus,
  addToNetWorth: IconTrendingUp,
  wallet: IconWallet,
  error: IconExclamationCircleFilled,
  actionButtonsTrigger: IconChevronUp,
  creditCardIcon: IconCreditCard,
  money: IconMoneybag,
  bank: IconBuildingBank,
  trendingUp: IconChartBarPopular,
  ellipsis: IconDotsVertical,
  edit: IconPencil,
  trash: IconTrash,
}